# Generated by Django 5.0 on 2023-12-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('address', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('socialMediaLink', models.URLField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField()),
                ('personalWebsiteLink', models.URLField(blank=True, null=True)),
                ('mapsPosition', models.CharField(max_length=255)),
                ('subscriptionID', models.IntegerField()),
                ('specialities', models.JSONField()),
                ('workingHours', models.JSONField()),
                ('workingDays', models.JSONField()),
            ],
        ),
    ]
