# Generated by Django 5.0 on 2023-12-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='profilePicture',
        ),
    ]
