# Generated by Django 5.0 on 2023-12-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0002_remove_lawyer_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='specialities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='workingDays',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='workingHours',
            field=models.TextField(),
        ),
    ]
