# Generated by Django 5.0 on 2023-12-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0004_lawyer_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
